### ISSUE TITLE
micrond @reboot

### ISSUE THREAD

**Issue by AKA-47** [freifunk-gluon/packages#124]
is it intentional that there is no @reboot trigger?

**Comment by AKA-47** [comment]
for example @reboot /lib/gluon/txpower-fix/fixtxpower.sh doesnt work

**Comment by NeoRaider** [comment]
@reboot doesn't really belong into a cron daemon, it's a misfeature in my opinion. Do it in an initscript or rc.local.

micrond is no full cron replacement anyways, for example it doesn't support user crontabs.
