### ISSUE TITLE
uci set autoupdater getting into otions instead of list

### ISSUE THREAD

**Issue by AKA-47** [freifunk-gluon/packages#127]
When i do:
uci set autoupdater.testing.mirror=http://MirrorURL

then cat /etc/config/autoupdater
is see:
config branch 'testing'
........
        option name 'testing'
---->        option mirror 'http://MirrorURL'

instead of:
       list mirror  'http://MirrorURL'

so autoupdater is failing:
/usr/bin/lua: /usr/sbin/autoupdater:301: bad argument #1 to 'remove' (table expected, got string)
stack traceback:
	[C]: in function 'remove'
	/usr/sbin/autoupdater:301: in main chunk
	[C]: ?

when i switch it manually everything works fine. is uci using an old option here?

is this a bug or a feature?

**Comment by NeoRaider** [comment]
You are using uci wrong. `uci set` ist used to set options, `uci add_list` and `uci remove_list` are used to configure lists.
