### ISSUE TITLE
Respondd information for active channels/txpower, batman nexthop and airtime

### ISSUE THREAD

**Issue by t-8ch** [freifunk-gluon/packages#138]
(Probably related to #67)

We created a package for Freifunk Frankfurt to provide:
- Configured channels/TX Power for wifi interfaces
- The batman nexthop
- Wifi airtime

Module: https://github.com/freifunk-ffm/ffffmlib-playground

The module is implemented as a shared library providing the functionality, a lua module using it , three alfred/old-respondd modules and two respondd modules.

We would like to have it integrated into gluon packages proper. For that I have some questions:
- Is this acceptable for gluon packages?
- Is this layout acceptable?

Of course I would remove all the `ffffm` strings.

Cc @oszilloskop, @eberhab

**Comment by NeoRaider** [comment]
I haven't had a deeper look at it yet, but I'd like to have such a package in Gluon. I'm not sure if the packages repo or the main repo is the best place for it. The packages repo is for packages which don't depend on Gluon and are supposed to be upstreamed to OpenWrt/LEDE eventually. At a glance, it doesn't seem like anything of this package depends on Gluon, so either might be an option.

Other comments:
* The "nexthop" provider is not only extremely misleading (in the batman-adv context, "nexthop" usually refers to the next node of a forwarding path, which is specific for each destination, and not to the gateway), it is also redundant, `gluon-mesh-batman-adv-core/src/respondd.c` already provides this field as "gateway"
* All Lua and "legacy" respondd parts should be removed from the package, the submitted package should just contain a single respondd provider (I don't have a strong opinion on splitting off the core functionality into another .so, but if you don't have a concrete usecase for reusing this code, it would make sense to merge everything into the respondd provider)

I haven't looked at the layout yet.

**Comment by t-8ch** [comment]
@NeoRaider 
* Should I open another issue in gluon?
* The `nexthop` is the other macaddress field from the `gateway` line in the batman adv line, it is not the same thing.
* Could we keep it and just not install it?
* Merging could be done by just linking it statically.

**Comment by eberhab** [comment]
The nexthop provider is an addition to the gateway information. Its is indeed next node of the forwarding path to the gateway.

**Comment by NeoRaider** [comment]
* A Gluon issue is not needed, one issue is enough
* Ah, indeed. Then that functionality should just be merged into `gluon-mesh-batman-adv-core/src/respondd.c`, and it should be made clear in the structure that this is the nexthop to the gateway.
* The package should only contain the parts that are required. What do you use the Lua parts for? If they are generally useful, they could become another package.

**Comment by t-8ch** [comment]
* Nice
* Also nice, the code came from there anyways. I'll open a PR. (Could you give an example for the structure? `gateway_nexthop`, or can we modify the existing `gateway` field)
* It would make it easier to integrate it into luci. But TBH its mostly boiler plate anyways. I'll remove it.

**Comment by rotanid** [comment]
@t-8ch are you still planning to do a PR for channels/txpower/airtime?

**Comment by genofire** [comment]
Maybe this one is PR ready https://github.com/FreifunkBremen/ffhb-packages/tree/breminale2016/ffhb/gluon-respondd-wifisettings
(It works for me and i have no time for a disscussion about the layout ... so if some own need it, copy it and make a PR)

**Comment by rotanid** [comment]
it looks like freifunk bremen also has a newer version of this:
https://github.com/FreifunkBremen/ffhb-packages/tree/master/ffhb/gluon-respondd-airtime
i can't comment on the C code, the only issue i see is, that it doesn't support more than two wifi devices.
maybe someone else with C-knowledge can fix this and do a PR to add this package to gluon

**Comment by rotanid** [comment]
for reference, part of it (nexthop) got included in https://github.com/freifunk-gluon/gluon/pull/795
the other part is being discussed/worked on in https://github.com/freifunk-gluon/gluon/pull/826

**Comment by rubo77** [comment]
Das klingt ja höchst interressant, kann vielleicht jemand auf deutsch kurz erklären, was ein nexthop hier sein soll?

Ich verstehe nicht ganz, was anders ist, zu den schon vorhandenen einstelungen für die sendeleistung im config mode, ist das nicht "TX Power"?

Was passiert mit der airtime in diesem Paket?
Also was genau will man mit diesem Paket erreichen?

**Comment by rotanid** [comment]
es geht darum, diese Informationen via respondd im mesh zu verbreiten.
bei der airtime geht es darum, die Information wie stark die airtime eben ausgenutzt ist zu erfassen und zu verbreiten.
Aber für solche Erklärungen, v.a. auf Deutsch, vielleicht besser in den IRC-Channel kommen ;-)

**Comment by rotanid** [comment]
this was fixed by merging #156
