### ISSUE TITLE
respondd-module-airtime: Allocation checks missing

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/packages#158]
Next to the checks missing as noted in #157 it seems like there are a few more allocation checks missing.

In the C standard, a NULL pointer dereference is undefined. While on Linux it usually just kills the program with a SIGSEGV, it seems that a NULL pointer dereference together with compiler optimizations can cause more serious issues. Read Tim Armstrong's reply here for instance (which references/summarizes an LLVM blog post):

https://www.quora.com/What-actually-happens-when-dereferencing-a-NULL-pointer

Currently unchecked allocation examples:

* [json_object_new_*()](https://github.com/freifunk-gluon/packages/blob/master/net/respondd-module-airtime/src/respondd.c#L16)
* [malloc()](https://github.com/freifunk-gluon/packages/blob/master/net/respondd-module-airtime/src/ifaces.c#L24)
* (and all nla_get_*()s and nla_parse() )

**Comment by T-X** [comment]
PS: The C reimplementation of respondd seems to be missing malloc() checks, too:

https://github.com/freifunk-gluon/packages/blob/master/net/respondd/src/respondd.c

**Comment by jplitza** [comment]
A kind of general question would be how to react to an allocation error: Terminate respondd as a whole or fail gracefully by continuing best-effort (e.g. by not adding the interface to the list of interfaces to report). While I think no single respondd module should quit the whole process (although it would be restarted by procd), continuing in the absence of free memory doesn't seem a plausible thing to do either.
