### ISSUE TITLE
respondd does not mark the "primary0" mac as the "MainIF/MAC"

### ISSUE THREAD

**Issue by Adorfer** [freifunk-gluon/packages#163]
the main batman-adv-mac "primary0" is not listed/marked explicitly. 
Since this primary0 is the one you need to now to use features like "batctl tp", it's a guessing-game to identify the right mac from the "mixed list". 
(propably it's the one ending on "b" or "3", but that's just a guess, it would be better to have it clearly identified on the datagrams provided by respondd.)

**Comment by NeoRaider** [comment]
Wrong repo, this is a data provider issue.

**Comment by NeoRaider** [comment]
New issue: https://github.com/freifunk-gluon/gluon/issues/1048
