### ISSUE TITLE
Respondd package with information of current isp

### ISSUE THREAD

**Issue by genofire** [freifunk-gluon/packages#166]
It would be cool, if respondd publish the "main" domain of reverse ip address.

On this way it is possible to detect the isp.

**Comment by NeoRaider** [comment]
... I have no idea what you're talking about. Which IP address? ISP of what?

Note that respondd data is public to anyone in the mesh, so there are also privacy concerns when adding new data.

**Comment by genofire** [comment]
Ups mean reverse dns of the public ip address.
So it would be of a `x590feead.dyn.telefonica.de` the value `telefonica.de` which would published by respondd.

**Comment by NeoRaider** [comment]
1. Usually a node doesn't know its public IP address, as the usual usecase is it plug in into a private (192.168.x.y) network
2. It is information a node should never publicly announce. It is really nobody's business what ISP you use.
3. A much better place to do such statistics would be the backbone servers, you can get this information from the fastd status socket. But still, I have privacy concerns and would strongly suggest not to collect such data at all.

**Comment by genofire** [comment]
You are right.
FYI: i just have a the idea to use the nodes as a notiify system for detect something like http://www.radiobremen.de/nachrichten/land_und_leute/probleme-vodafone100.html
