### ISSUE TITLE
respondd-module-airtime: Don't complain without wifi?

### ISSUE THREAD

**Issue by jplitza** [freifunk-gluon/packages#167]
When executed in a VM for example, I see the following in the logs a lot:
```
respondd[2552]: netlink.c: error on line 28
```
The `netlink.c` actually is from respondd-module-airtime, and it's probably caused by the lack of wifi interfaces and thus the lack of netlink answers.

**Comment by NeoRaider** [comment]
Uhm yes. First of all, the error message should be a bit more descriptive, and I agree that errors caused by the kernel not having WLAN support should simply be ignored.

**Comment by jplitza** [comment]
I added more meaningful error messages in 7ba3cf8 but can't seem to reproduce the issue now, so I'm closing this for the moment.
