### ISSUE TITLE
autoupdater: doesn't care about sysupgrade exit code

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/packages#193]
this issue was detected during https://github.com/freifunk-gluon/gluon/issues/1496
currently, the new autoupdater doesn't handle the exit code of the sysupgrade script it calls.
therefore, it doesn't put the node back into an accessible or working state after sysupgrade fails - a manual power cycle is necessary in this case.

**Comment by Adorfer** [comment]
I am using this modified sysupgrade, just to make sure not to put the node into freeze if sysupgrade fails. 
(Yes, this is not fine for normal use, but better than risking a freeze with need of powercycle)
https://gist.github.com/Adorfer/3c60347cf8599beed6c0f2d2124e95f5#174

**Comment by rotanid** [comment]
related issues:
#2742
#3181
