### ISSUE TITLE
autoupdater: Firmware version 1.7.0 not considered newer than 1.7.0~rc1

### ISSUE THREAD

**Issue by RalfJung** [freifunk-gluon/packages#208]
It used to be the case that (following Debian's handling of version numbers) firmware version 1.7.0 was considered newer than 1.7.0\~rc1.  However, with the latest gluon 2018.1.3, that does not seem to work any more: We have rolled out 1.7.0\~rc1 on our beta branch, and now we built 1.7.0, but even when doing a force update check the autoupdater just says "No new firmware available."

**Comment by rubo77** [comment]
Isn't this a bug? `~` should be not handled in a string-comparism way, but should be always smaller, meaning:

>With a lexicographic order, a string is always sorted before its prefix. The tilde character allows a deviation from that: foo~bar is always sorted before foo as well as before any version that begins with foo followed by a character other than ~. This is often used for beta versions: 8u60~b22 is sorted before 8u60. I don't know why the OpenJDK 8 packages seem to alternate between -b and ~b suffixes though.

see https://unix.stackexchange.com/a/230921/20661

Tilde should be used especially for the case **release-candidates**
