### ISSUE TITLE
create v2018.2.x branch and backport bugfixes

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/packages#220]
as agreed on @IRC, there needs to be a v2018.2.x packages branch which does not contain everything the master branch now has.

**Comment by NeoRaider** [comment]
Actually, I'm not sure if any of the commits after the tunneldigger update qualify for v2018.2.x.

**Comment by rotanid** [comment]
that's up to you as the author of most of these :)

**Comment by rotanid** [comment]
maybe in the meantime there are commits eligible for v2018.2.x ?

**Comment by NeoRaider** [comment]
v2018.2.x was updated to 524ae77. A branch can be created when more bugfixes are necessary.
