### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by Sprinterfreak** [freifunk-gluon/packages#221]
https://github.com/freifunk-gluon/packages/blob/9a364fb8d0a4f9fecb6a3aac7525fedf759fe81a/net/respondd/src/respondd.c#L623
iface->max_multicast_delay can be $1 = 0 wich crashes respondd with arithmetic exception.

**Comment by NeoRaider** [comment]
Fixed in 9a364fb8d0a4f9fecb6a3aac7525fedf759fe81a.
