### ISSUE TITLE
tunneldigger: unnecessary kmod-l2tp-ip dependency?

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/packages#242]
The Tunneldigger OpenWrt Makefile currently depends on on the kmod packages `kmod-l2tp`, `kmod-l2tp-eth` and `kmod-l2tp-ip`. `kmod-l2tp-ip` shouldn't be needed, as Tunneldigger uses the UDP L2TP transport and not raw IP.

Am I overlooking something, or can this dependency be removed? I have not tried removing it myself, as I don't have a Tunneldigger setup to test the change.

cc @RalfJung @kaechele

**Comment by kaechele** [comment]
I can confirm that Tunneldigger does not require the `l2tp_ip` module at all to function.

**Comment by RalfJung** [comment]
Is there something we should change in the tunneldigger repo to document this?

**Comment by kaechele** [comment]
> Is there something we should change in the tunneldigger repo to document this?

Not really. There is only one mention of it in the Travis CI YAML file where it is (unnecessarily) loaded.
